### ISSUE TITLE
Hash tables, mutability

### ISSUE THREAD

**Issue by bitemyapp** [sweirich/hs-inferno#1]
>I was unable to find a generic implementation of hashtables

I was curious about this and someone was able to surmise that you meant generic over `IO` and `ST`, with that in mind, I'm curious why you didn't use an `IORef` or `TVar` of a containers `Map`. Is it because you were trying to stay true to the original OCaml library, because you anticipate spammy updates making a data structure like this win out, or something else?

Thanks for publishing this!

**Comment by sweirich** [comment]
Hi, 

Thanks for the question!  I haven't looked at this project for almost two years.  I believe that my motivation then was to stay true to the original OCaml library; which I was trying to understand in greater depth.
